### ISSUE TITLE
Add basic contact form

### ISSUE THREAD

**Issue by hatzipanis** [batchnz/gatsby-starter-batch#13]
Using [Netlify Forms](https://www.netlify.com/docs/form-handling/).

**Comment by max8hine** [comment]
For advanced validating, please consider [Formik](https://jaredpalmer.com/formik)

**Comment by hatzipanis** [comment]
Thanks @max8hine - do you know how well this will work with Gastby and Netlify?

**Comment by hatzipanis** [comment]
Closes #16
