### ISSUE TITLE
Add stylelint PostCSS plugin

### ISSUE THREAD

**Issue by hatzipanis** [batchnz/gatsby-starter-batch#15]
Improve our CSS quality by implementing [stylelint](https://stylelint.io/) as well as the [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended) config.

**Comment by max8hine** [comment]
stylelint could config as PostCss plugin with few issues with it, such as do not respect `.stylelintignore` file, and stylelint author comment as `It's generally recommended to use stylelint as a standalone tool`, so this reason, We will using following tools to implementing stylelint.

- [ ] [stylelint-webpack-plugin](https://github.com/danbruegge/gatsby-plugin-stylelint)
- [ ] [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended)

**Comment by hatzipanis** [comment]
Resolved by #19 - cheers @max8hine!
