### ISSUE TITLE
og:image and twitter:image not working

### ISSUE THREAD

**Issue by max8hine** [batchnz/gatsby-starter-batch#31]
twitter scraper and facebook scraper do not recognise react component. so need to be hardcode data for the image URL.

**Comment by hatzipanis** [comment]
Max once you've resolved #36 please review this again.

**Comment by max8hine** [comment]
Twitter Card validator pass

![image](https://user-images.githubusercontent.com/15165714/48106777-ca831380-e2a1-11e8-8463-c199403113af.png)

**Comment by max8hine** [comment]
Facebook Card Pass
![image](https://user-images.githubusercontent.com/15165714/48106837-0b7b2800-e2a2-11e8-812f-25faf34a6bb1.png)
